import json
import os
from config import bot

LANGUAGE_FILE = "language_data.json"
DEFAULT_LANGUAGE = "EN-GB"

TRANSLATIONS = {
    "EN-GB": {
        # Existing admins.py translations
        "must_be_admin": "You must be an admin to use this command.",
        "no_permission_promote_demote": "You don't have permission to promote or demote users.",
        "error_checking_admin": "Error checking admin status: {error}",
        "error_checking_permissions": "Error checking permissions: {error}",
        "promote_usage": "Usage → /promote [user_id] or reply to user message.\n\nOr /promote [user_id] [title].\n\nOr /promote [user_id] [title] [duration].\n(e.g., /promote 123366 moderator 1d)",
        "invalid_user_ref": "Invalid user reference.",
        "user_not_found": "User not found in this chat: {error}",
        "invalid_duration_format": "Invalid duration format: {duration}. Use m, h, or d (e.g., 30m, 2h, 1d).",
        "duration_positive": "Duration must be a positive value.",
        "title_too_long": "Title must be 16 characters or less!",
        "already_admin": "{user} is already an admin.",
        "promote_success": "Successfully promoted {user}\n\nPermissions:\n- Change info: True\n- Delete messages: True\n- Restrict members: True\n- Invite users: True\n- Pin messages: True\n- Promote members: False\n- Manage video chats: True",
        "title_set": "\n\nTitle set: {title}",
        "duration_set": "\nDuration: {duration}",
        "promote_failed": "Promotion failed: {error}",
        "no_permission_promote": "I don't have permission to promote users.",
        "too_many_admins": "Too many admins! Maximum is 50.",
        "user_not_member": "User is not a member of this chat.",
        "demote_usage": "Usage → /demote [user_id] or reply to user message.\n\nOr /demote [user_id].",
        "cannot_demote_owner": "You can't demote the group owner.",
        "not_admin": "{user} is not an admin.",
        "demote_success": "Successfully demoted {user}\n\nPermissions:\n- Change info: False\n- Delete messages: False\n- Restrict members: False\n- Invite users: False\n- Pin messages: False\n- Promote members: False\n- Manage video chats: False",
        "demote_failed": "Demotion failed: {error}",
        "no_permission_demote": "I don't have permission to demote users!",
        "no_admins_found": "No admins found.",
        "admin_list": "Admins in {chat_title}\n{admin_list}",
        "admin_list_failed": "Failed to retrieve admin list: {error}",
        "cache_refreshed": "Admin cache refreshed successfully.",
        "cache_refresh_failed": "Cache refresh failed: {error}",
        "anonadmin_status": "Anonymous admin mode is currently {status}.",
        "anonadmin_updated": "Anonymous admin mode {status}!",
        "anonadmin_failed": "Failed to update settings: {error}",
        "adminerror_status": "Admin error messages are currently {status}.",
        "adminerror_updated": "Admin error messages {status}!",
        "adminerror_failed": "Failed to update settings: {error}",
        "setlan_usage": "Usage: /setlan [language_code]\nAvailable languages: {languages}",
        "invalid_language": "Invalid language code: {code}. Use /setlan to see available languages.",
        "language_updated": "Language set to {language}.",
        # Existing bans.py translations
        "no_user_id": "Please reply to a message or provide a user ID!",
        "cannot_ban_admin": "Cannot ban an admin or creator!",
        "cannot_ban_bot": "Cannot ban a bot!",
        "already_banned": "User is already banned!",
        "ban_success": "User {user} has been banned! Action by {admin}",
        "no_permission_ban": "I don't have permission to ban users! Please check my admin rights.",
        "ban_admin_error": "Cannot ban an admin!",
        "ban_error": "Error banning user: {error}",
        "silent_ban_error": "Error silently banning user: {error}",
        "tban_usage": "Usage: /tban [user_id/reply] [duration] (e.g., 1h, 30m, 2d)",
        "tban_duration_invalid": "Invalid duration format! Use [number] [s|m|h|d|w] (e.g., 1h, 30m, 2d)",
        "tban_duration_too_long": "Duration cannot exceed 366 days!",
        "tban_success": "User {user} has been temporarily banned for {duration}! Action by {admin}",
        "tban_error": "Error temporarily banning user: {error}",
        "dban_no_reply": "Please reply to a message to use /dban!",
        "dban_success": "User {user} has been banned and their message deleted! Action by {admin}",
        "dban_delete_error": "User banned but failed to delete message: {error}",
        "dban_error": "Error banning and deleting message: {error}",
        "rban_success": "User {user} has been randomly banned for {duration}! Action by {admin}",
        "rban_error": "Error randomly banning user: {error}",
        "unexpected_error": "Unexpected error: {error}",
        # New rules.py translations
        "no_rules_set": "No rules set for this chat.",
        "view_private_rules": "Click the button below to view the rules:",
        "setrules_usage": "Please provide the rules text. Usage: /setrules [text]",
        "rules_updated": "Rules updated successfully! Share rules with this deep link: {deep_link}",
        "privaterules_usage": "Usage: /privaterules [yes/no/on/off]",
        "privaterules_status": "Private rules {status}.",
        "rules_reset": "Rules reset to default.",
        "setrulesbutton_usage": "Please provide the button name. Usage: /setrulesbutton [name]",
        "rulesbutton_set": "Rules button name set to: {button_name}",
        "rulesbutton_reset": "Rules button name reset to default."
    },
    "HI": {
        # Existing admins.py translations
        "must_be_admin": "इस कमांड का उपयोग करने के लिए आपको प्रशासक होना चाहिए।",
        "no_permission_promote_demote": "आपको उपयोगकर्ताओं को प्रोमोट या डिमोट करने की अनुमति नहीं है।",
        "error_checking_admin": "प्रशासक स्थिति जांचने में त्रुटि: {error}",
        "error_checking_permissions": "अनुमतियों की जांच में त्रुटि: {error}",
        "promote_usage": "उपयोग → /promote [user_id] या उपयोगकर्ता संदेश का जवाब दें।\n\nया /promote [user_id] [title].\n\nया /promote [user_id] [title] [duration].\n(उदाहरण, /promote 123366 मॉडरेटर 1d)",
        "invalid_user_ref": "अमान्य उपयोगकर्ता संदर्भ।",
        "user_not_found": "इस चैट में उपयोगकर्ता नहीं मिला: {error}",
        "invalid_duration_format": "अमान्य अवधि प्रारूप: {duration}। m, h, या d का उपयोग करें (उदाहरण, 30m, 2h, 1d)।",
        "duration_positive": "अवधि एक सकारात्मक मान होनी चाहिए।",
        "title_too_long": "शीर्षक 16 अक्षरों से कम होना चाहिए!",
        "already_admin": "{user} पहले से ही प्रशासक है।",
        "promote_success": "{user} को सफलतापूर्वक प्रोमोट किया गया\n\nअनुमतियाँ:\n- जानकारी बदलें: सत्य\n- संदेश हटाएँ: सत्य\n- सदस्यों को प्रतिबंधित करें: सत्य\n- उपयोगकर्ताओं को आमंत्रित करें: सत्य\n- संदेश पिन करें: सत्य\n- सदस्यों को प्रोमोट करें: असत्य\n- वीडियो चैट प्रबंधन: सत्य",
        "title_set": "\n\nशीर्षक सेट: {title}",
        "duration_set": "\nअवधि: {duration}",
        "promote_failed": "प्रोमोशन विफल: {error}",
        "no_permission_promote": "मुझे उपयोगकर्ताओं को प्रोमोट करने की अनुमति नहीं है।",
        "too_many_admins": "बहुत सारे प्रशासक! अधिकतम 50 है।",
        "user_not_member": "उपयोगकर्ता इस चैट का सदस्य नहीं है।",
        "demote_usage": "उपयोग → /demote [user_id] या उपयोगकर्ता संदेश का जवाब दें।\n\nया /demote [user_id].",
        "cannot_demote_owner": "आप समूह के मालिक को डिमोट नहीं कर सकते।",
        "not_admin": "{user} प्रशासक नहीं है।",
        "demote_success": "{user} को सफलतापूर्वक डिमोट किया गया\n\nअनुमतियाँ:\n- जानकारी बदलें: असत्य\n- संदेश हटाएँ: असत्य\n- सदस्यों को प्रतिबंधित करें: असत्य\n- उपयोगकर्ताओं को आमंत्रित करें: असत्य\n- संदेश पिन करें: असत्य\n- सदस्यों को प्रोमोट करें: असत्य\n- वीडियो चैट प्रबंधन: असत्य",
        "demote_failed": "डिमोशन विफल: {error}",
        "no_permission_demote": "मुझे उपयोगकर्ताओं को डिमोट करने की अनुमति नहीं है!",
        "no_admins_found": "कोई प्रशासक नहीं मिला।",
        "admin_list": "{chat_title} में प्रशासक\n{admin_list}",
        "admin_list_failed": "प्रशासक सूची प्राप्त करने में विफल: {error}",
        "cache_refreshed": "प्रशासक कैश सफलतापूर्वक ताज़ा किया गया।",
        "cache_refresh_failed": "कैश ताज़ा करने में विफल: {error}",
        "anonadmin_status": "अनाम प्रशासक मोड वर्तमान में {status} है।",
        "anonadmin_updated": "अनाम प्रशासक मोड {status}!",
        "anonadmin_failed": "सेटिंग्स अपडेट करने में विफल: {error}",
        "adminerror_status": "प्रशासक त्रुटि संदेश वर्तमान में {status} हैं।",
        "adminerror_updated": "प्रशासक त्रुटि संदेश {status}!",
        "adminerror_failed": "सेटिंग्स अपडेट करने में विफल: {error}",
        "setlan_usage": "उपयोग: /setlan [language_code]\nउपलब्ध भाषाएँ: {languages}",
        "invalid_language": "अमान्य भाषा कोड: {code}। उपलब्ध भाषाओं के लिए /setlan का उपयोग करें।",
        "language_updated": "भाषा {language} पर सेट की गई।",
        # Existing bans.py translations
        "no_user_id": "कृपया किसी संदेश का जवाब दें या उपयोगकर्ता आईडी प्रदान करें!",
        "cannot_ban_admin": "प्रशासक या निर्माता को प्रतिबंधित नहीं किया जा सकता!",
        "cannot_ban_bot": "बॉट को प्रतिबंधित नहीं किया जा सकता!",
        "already_banned": "उपयोगकर्ता पहले से ही प्रतिबंधित है!",
        "ban_success": "उपयोगकर्ता {user} को प्रतिबंधित कर दिया गया है! कार्रवाई {admin} द्वारा",
        "no_permission_ban": "मुझे उपयोगकर्ताओं को प्रतिबंधित करने की अनुमति नहीं है! कृपया मेरे प्रशासक अधिकारों की जांच करें।",
        "ban_admin_error": "प्रशासक को प्रतिबंधित नहीं किया जा सकता!",
        "ban_error": "उपयोगकर्ता को प्रतिबंधित करने में त्रुटि: {error}",
        "silent_ban_error": "उपयोगकर्ता को चुपके से प्रतिबंधित करने में त्रुटि: {error}",
        "tban_usage": "उपयोग: /tban [user_id/reply] [duration] (उदाहरण, 1h, 30m, 2d)",
        "tban_duration_invalid": "अमान्य अवधि प्रारूप! [number][s|m|h|d|w] का उपयोग करें (उदाहरण, 1h, 30m, 2d)",
        "tban_duration_too_long": "अवधि 366 दिनों से अधिक नहीं हो सकती!",
        "tban_success": "उपयोगकर्ता {user} को {duration} के लिए अस्थायी रूप से प्रतिबंधित किया गया है! कार्रवाई {admin} द्वारा",
        "tban_error": "उपयोगकर्ता को अस्थायी रूप से प्रतिबंधित करने में त्रुटि: {error}",
        "dban_no_reply": "/dban का उपयोग करने के लिए कृपया किसी संदेश का जवाब दें!",
        "dban_success": "उपयोगकर्ता {user} को प्रतिबंधित कर दिया गया और उनका संदेश हटा दिया गया! कार्रवाई {admin} द्वारा",
        "dban_delete_error": "उपयोगकर्ता प्रतिबंधित लेकिन संदेश हटाने में विफल: {error}",
        "dban_error": "प्रतिबंध और संदेश हटाने में त्रुटि: {error}",
        "rban_success": "उपयोगकर्ता {user} को {duration} के लिए यादृच्छिक रूप से प्रतिबंधित किया गया है! कार्रवाई {admin} द्वारा",
        "rban_error": "उपयोगकर्ता को यादृच्छिक रूप से प्रतिबंधित करने में त्रुटि: {error}",
        "unexpected_error": "अप्रत्याशित त्रुटि: {error}",
        # New rules.py translations
        "no_rules_set": "इस चैट के लिए कोई नियम सेट नहीं किए गए हैं।",
        "view_private_rules": "नियम देखने के लिए नीचे दिए गए बटन पर क्लिक करें:",
        "setrules_usage": "कृपया नियमों का पाठ प्रदान करें। उपयोग: /setrules [text]",
        "rules_updated": "नियम सफलतापूर्वक अपडेट किए गए! इस डीप लिंक के साथ नियम साझा करें: {deep_link}",
        "privaterules_usage": "उपयोग: /privaterules [yes/no/on/off]",
        "privaterules_status": "निजी नियम {status}।",
        "rules_reset": "नियम डिफ़ॉल्ट पर रीसेट किए गए।",
        "setrulesbutton_usage": "कृपया बटन का नाम प्रदान करें। उपयोग: /setrulesbutton [name]",
        "rulesbutton_set": "नियम बटन का नाम सेट किया गया: {button_name}",
        "rulesbutton_reset": "नियम बटन का नाम डिफ़ॉल्ट पर रीसेट किया गया।"
    },
    "AR": {
        # Existing admins.py translations
        "must_be_admin": "يجب أن تكون مشرفًا لاستخدام هذا الأمر.",
        "no_permission_promote_demote": "ليس لديك إذن لترقية أو تخفيض المستخدمين.",
        "error_checking_admin": "خطأ في التحقق من حالة المشرف: {error}",
        "error_checking_permissions": "خطأ في التحقق من الأذونات: {error}",
        "promote_usage": "الاستخدام → /promote [user_id] أو الرد على رسالة المستخدم.\n\nأو /promote [user_id] [title].\n\nأو /promote [user_id] [title] [duration].\n(مثال، /promote 123366 مشرف 1d)",
        "invalid_user_ref": "مرجع مستخدم غير صالح.",
        "user_not_found": "لم يتم العثور على المستخدم في هذه الدردشة: {error}",
        "invalid_duration_format": "تنسيق المدة غير صالح: {duration}. استخدم m، h، أو d (مثال، 30m، 2h، 1d).",
        "duration_positive": "يجب أن تكون المدة قيمة إيجابية.",
        "title_too_long": "يجب أن يكون العنوان 16 حرفًا أو أقل!",
        "already_admin": "{user} هو بالفعل مشرف.",
        "promote_success": "تمت ترقية {user} بنجاح\n\nالأذونات:\n- تغيير المعلومات: نعم\n- حذف الرسائل: نعم\n- تقييد الأعضاء: نعم\n- دعوة المستخدمين: نعم\n- تثبيت الرسائل: نعم\n- ترقية الأعضاء: لا\n- إدارة الدردشات المرئية: نعم",
        "title_set": "\n\nتم تعيين العنوان: {title}",
        "duration_set": "\nالمدة: {duration}",
        "promote_failed": "فشل الترقية: {error}",
        "no_permission_promote": "ليس لدي إذن لترقية المستخدمين.",
        "too_many_admins": "المشرفون كثيرون جدًا! الحد الأقصى هو 50.",
        "user_not_member": "المستخدم ليس عضوًا في هذه الدردشة.",
        "demote_usage": "الاستخدام → /demote [user_id] أو الرد على رسالة المستخدم.\n\nأو /demote [user_id].",
        "cannot_demote_owner": "لا يمكنك تخفيض مالك المجموعة.",
        "not_admin": "{user} ليس مشرفًا.",
        "demote_success": "تم تخفيض {user} بنجاح\n\nالأذونات:\n- تغيير المعلومات: لا\n- حذف الرسائل: لا\n- تقييد الأعضاء: لا\n- دعوة المستخدمين: لا\n- تثبيت الرسائل: لا\n- ترقية الأعضاء: لا\n- إدارة الدردشات المرئية: لا",
        "demote_failed": "فشل التخفيض: {error}",
        "no_permission_demote": "ليس لدي إذن لتخفيض المستخدمين!",
        "no_admins_found": "لم يتم العثور على مشرفين.",
        "admin_list": "المشرفون في {chat_title}\n{admin_list}",
        "admin_list_failed": "فشل في استرجاع قائمة المشرفين: {error}",
        "cache_refreshed": "تم تحديث ذاكرة المشرفين بنجاح.",
        "cache_refresh_failed": "فشل تحديث الذاكرة: {error}",
        "anonadmin_status": "وضع المشرف المجهول حاليًا {status}.",
        "anonadmin_updated": "وضع المشرف المجهول {status}!",
        "anonadmin_failed": "فشل في تحديث الإعدادات: {error}",
        "adminerror_status": "رسائل خطأ المشرف حاليًا {status}.",
        "adminerror_updated": "رسائل خطأ المشرف {status}!",
        "adminerror_failed": "فشل في تحديث الإعدادات: {error}",
        "setlan_usage": "الاستخدام: /setlan [language_code]\nاللغات المتاحة: {languages}",
        "invalid_language": "رمز اللغة غير صالح: {code}. استخدم /setlan لمعرفة اللغات المتاحة.",
        "language_updated": "تم تعيين اللغة إلى {language}.",
        # Existing bans.py translations
        "no_user_id": "يرجى الرد على رسالة أو تقديم معرف المستخدم!",
        "cannot_ban_admin": "لا يمكن حظر مشرف أو مالك!",
        "cannot_ban_bot": "لا يمكن حظر بوت!",
        "already_banned": "المستخدم محظور بالفعل!",
        "ban_success": "تم حظر المستخدم {user}! الإجراء بواسطة {admin}",
        "no_permission_ban": "ليس لدي إذن لحظر المستخدمين! يرجى التحقق من حقوق المشرف الخاصة بي.",
        "ban_admin_error": "لا يمكن حظر مشرف!",
        "ban_error": "خطأ في حظر المستخدم: {error}",
        "silent_ban_error": "خطأ في حظر المستخدم بصمت: {error}",
        "tban_usage": "الاستخدام: /tban [user_id/reply] [duration] (مثال، 1h، 30m، 2d)",
        "tban_duration_invalid": "تنسيق المدة غير صالح! استخدم [number][s|m|h|d|w] (مثال، 1h، 30m، 2d)",
        "tban_duration_too_long": "لا يمكن أن تتجاوز المدة 366 يومًا!",
        "tban_success": "تم حظر المستخدم {user} مؤقتًا لمدة {duration}! الإجراء بواسطة {admin}",
        "tban_error": "خطأ في حظر المستخدم مؤقتًا: {error}",
        "dban_no_reply": "يرجى الرد على رسالة لاستخدام /dban!",
        "dban_success": "تم حظر المستخدم {user} وحذف رسالته! الإجراء بواسطة {admin}",
        "dban_delete_error": "تم حظر المستخدم ولكن فشل حذف الرسالة: {error}",
        "dban_error": "خطأ في حظر وحذف الرسالة: {error}",
        "rban_success": "تم حظر المستخدم {user} عشوائيًا لمدة {duration}! الإجراء بواسطة {admin}",
        "rban_error": "خطأ في حظر المستخدم عشوائيًا: {error}",
        "unexpected_error": "خطأ غير متوقع: {error}",
        # New rules.py translations
        "no_rules_set": "لم يتم تعيين قواعد لهذه الدردشة.",
        "view_private_rules": "انقر على الزر أدناه لعرض القواعد:",
        "setrules_usage": "يرجى تقديم نص القواعد. الاستخدام: /setrules [text]",
        "rules_updated": "تم تحديث القواعد بنجاح! شارك القواعد مع هذا الرابط العميق: {deep_link}",
        "privaterules_usage": "الاستخدام: /privaterules [yes/no/on/off]",
        "privaterules_status": "القواعد الخاصة {status}.",
        "rules_reset": "تم إعادة تعيين القواعد إلى الوضع الافتراضي.",
        "setrulesbutton_usage": "يرجى تقديم اسم الزر. الاستخدام: /setrulesbutton [name]",
        "rulesbutton_set": "تم تعيين اسم زر القواعد إلى: {button_name}",
        "rulesbutton_reset": "تم إعادة تعيين اسم زر القواعد إلى الوضع الافتراضي."
    },
    "ZH-CN": {
        # Existing admins.py translations
        "must_be_admin": "您必须是管理员才能使用此命令。",
        "no_permission_promote_demote": "您没有权限提升或降级用户。",
        "error_checking_admin": "检查管理员状态时出错：{error}",
        "error_checking_permissions": "检查权限时出错：{error}",
        "promote_usage": "用法 → /promote [user_id] 或回复用户消息。\n\n或 /promote [user_id] [title]。\n\n或 /promote [user_id] [title] [duration]。\n（例如，/promote 123366 版主 1d）",
        "invalid_user_ref": "无效的用户引用。",
        "user_not_found": "在此聊天中未找到用户：{error}",
        "invalid_duration_format": "无效的持续时间格式：{duration}。请使用 m、h 或 d（例如，30m、2h、1d）。",
        "duration_positive": "持续时间必须是正值。",
        "title_too_long": "标题必须为 16 个字符或更少！",
        "already_admin": "{user} 已经是管理员。",
        "promote_success": "成功提升 {user}\n\n权限：\n- 更改信息：是\n- 删除消息：是\n- 限制成员：是\n- 邀请用户：是\n- 置顶消息：是\n- 提升成员：否\n- 管理视频聊天：是",
        "title_set": "\n\n标题设置：{title}",
        "duration_set": "\n持续时间：{duration}",
        "promote_failed": "提升失败：{error}",
        "no_permission_promote": "我没有权限提升用户。",
        "too_many_admins": "管理员过多！最多 50 个。",
        "user_not_member": "用户不是此聊天的成员。",
        "demote_usage": "用法 → /demote [user_id] 或回复用户消息。\n\n或 /demote [user_id]。",
        "cannot_demote_owner": "您无法降级群主。",
        "not_admin": "{user} 不是管理员。",
        "demote_success": "成功降级 {user}\n\n权限：\n- 更改信息：否\n- 删除消息：否\n- 限制成员：否\n- 邀请用户：否\n- 置顶消息：否\n- 提升成员：否\n- 管理视频聊天：否",
        "demote_failed": "降级失败：{error}",
        "no_permission_demote": "我没有权限降级用户！",
        "no_admins_found": "未找到管理员。",
        "admin_list": "{chat_title} 中的管理员\n{admin_list}",
        "admin_list_failed": "无法检索管理员列表：{error}",
        "cache_refreshed": "管理员缓存已成功刷新。",
        "cache_refresh_failed": "缓存刷新失败：{error}",
        "anonadmin_status": "匿名管理员模式当前为 {status}。",
        "anonadmin_updated": "匿名管理员模式 {status}！",
        "anonadmin_failed": "无法更新设置：{error}",
        "adminerror_status": "管理员错误消息当前为 {status}。",
        "adminerror_updated": "管理员错误消息 {status}！",
        "adminerror_failed": "无法更新设置：{error}",
        "setlan_usage": "用法：/setlan [language_code]\n可用语言：{languages}",
        "invalid_language": "无效的语言代码：{code}。请使用 /setlan 查看可用语言。",
        "language_updated": "语言设置为 {language}。",
        # Existing bans.py translations
        "no_user_id": "请回复一条消息或提供用户ID！",
        "cannot_ban_admin": "无法封禁管理员或群主！",
        "cannot_ban_bot": "无法封禁机器人！",
        "already_banned": "用户已被封禁！",
        "ban_success": "用户 {user} 已被封禁！由 {admin} 执行",
        "no_permission_ban": "我没有权限封禁用户！请检查我的管理员权限。",
        "ban_admin_error": "无法封禁管理员！",
        "ban_error": "封禁用户时出错：{error}",
        "silent_ban_error": "静默封禁用户时出错：{error}",
        "tban_usage": "用法：/tban [user_id/reply] [duration]（例如，1h、30m、2d）",
        "tban_duration_invalid": "无效的持续时间格式！请使用 [number][s|m|h|d|w]（例如，1h、30m、2d）",
        "tban_duration_too_long": "持续时间不能超过366天！",
        "tban_success": "用户 {user} 已被临时封禁 {duration}！由 {admin} 执行",
        "tban_error": "临时封禁用户时出错：{error}",
        "dban_no_reply": "请回复一条消息以使用 /dban！",
        "dban_success": "用户 {user} 已被封禁，其消息已删除！由 {admin} 执行",
        "dban_delete_error": "用户已封禁，但删除消息失败：{error}",
        "dban_error": "封禁并删除消息时出错：{error}",
        "rban_success": "用户 {user} 已被随机封禁 {duration}！由 {admin} 执行",
        "rban_error": "随机封禁用户时出错：{error}",
        "unexpected_error": "意外错误：{error}",
        # New rules.py translations
        "no_rules_set": "此聊天未设置规则。",
        "view_private_rules": "请点击下方按钮查看规则：",
        "setrules_usage": "请提供规则文本。用法：/setrules [text]",
        "rules_updated": "规则已成功更新！使用此深层链接分享规则：{deep_link}",
        "privaterules_usage": "用法：/privaterules [yes/no/on/off]",
        "privaterules_status": "私有规则 {status}。",
        "rules_reset": "规则已重置为默认。",
        "setrulesbutton_usage": "请提供按钮名称。用法：/setrulesbutton [name]",
        "rulesbutton_set": "规则按钮名称已设置为：{button_name}",
        "rulesbutton_reset": "规则按钮名称已重置为默认。"
    },
    "JA": {
        # Existing admins.py translations
        "must_be_admin": "このコマンドを使用するには管理者である必要があります。",
        "no_permission_promote_demote": "ユーザーを昇格または降格する権限がありません。",
        "error_checking_admin": "管理者ステータスの確認中にエラーが発生しました：{error}",
        "error_checking_permissions": "権限の確認中にエラーが発生しました：{error}",
        "promote_usage": "使用法 → /promote [user_id] またはユーザーメッセージに返信。\n\nまたは /promote [user_id] [title]。\n\nまたは /promote [user_id] [title] [duration]。\n（例：/promote 123366 モデレーター 1d）",
        "invalid_user_ref": "無効なユーザー参照。",
        "user_not_found": "このチャットでユーザーが見つかりませんでした：{error}",
        "invalid_duration_format": "無効な期間フォーマット：{duration}。m、h、または d を使用してください（例：30m、2h、1d）。",
        "duration_positive": "期間は正の値でなければなりません。",
        "title_too_long": "タイトルは16文字以下でなければなりません！",
        "already_admin": "{user} はすでに管理者です。",
        "promote_success": "{user} を正常に昇格しました\n\n権限：\n- 情報変更：はい\n- メッセージ削除：はい\n- メンバー制限：はい\n- ユーザー招待：はい\n- メッセージピン：はい\n- メンバー昇格：いいえ\n- ビデオチャット管理：はい",
        "title_set": "\n\nタイトル設定：{title}",
        "duration_set": "\n期間：{duration}",
        "promote_failed": "昇格に失敗しました：{error}",
        "no_permission_promote": "ユーザーを昇格する権限がありません。",
        "too_many_admins": "管理者が多すぎます！最大50人です。",
        "user_not_member": "ユーザーはこのチャットのメンバーではありません。",
        "demote_usage": "使用法 → /demote [user_id] またはユーザーメッセージに返信。\n\nまたは /demote [user_id]。",
        "cannot_demote_owner": "グループのオーナーを降格することはできません。",
        "not_admin": "{user} は管理者ではありません。",
        "demote_success": "{user} を正常に降格しました\n\n権限：\n- 情報変更：いいえ\n- メッセージ削除：いいえ\n- メンバー制限：いいえ\n- ユーザー招待：いいえ\n- メッセージピン：いいえ\n- メンバー昇格：いいえ\n- ビデオチャット管理：いいえ",
        "demote_failed": "降格に失敗しました：{error}",
        "no_permission_demote": "ユーザーを降格する権限がありません！",
        "no_admins_found": "管理者が見つかりませんでした。",
        "admin_list": "{chat_title} の管理者\n{admin_list}",
        "admin_list_failed": "管理者リストの取得に失敗しました：{error}",
        "cache_refreshed": "管理者キャッシュが正常に更新されました。",
        "cache_refresh_failed": "キャッシュの更新に失敗しました：{error}",
        "anonadmin_status": "匿名管理者モードは現在 {status} です。",
        "anonadmin_updated": "匿名管理者モード {status}！",
        "anonadmin_failed": "設定の更新に失敗しました：{error}",
        "adminerror_status": "管理者エラーメッセージは現在 {status} です。",
        "adminerror_updated": "管理者エラーメッセージ {status}！",
        "adminerror_failed": "設定の更新に失敗しました：{error}",
        "setlan_usage": "使用法：/setlan [language_code]\n利用可能な言語：{languages}",
        "invalid_language": "無効な言語コード：{code}。利用可能な言語を確認するには /setlan を使用してください。",
        "language_updated": "言語が {language} に設定されました。",
        # Existing bans.py translations
        "no_user_id": "メッセージに返信するか、ユーザーIDを指定してください！",
        "cannot_ban_admin": "管理者または作成者をBANすることはできません！",
        "cannot_ban_bot": "ボットをBANすることはできません！",
        "already_banned": "ユーザーはすでにBANされています！",
        "ban_success": "ユーザー {user} がBANされました！ {admin} によるアクション",
        "no_permission_ban": "ユーザーをBANする権限がありません！私の管理者権限を確認してください。",
        "ban_admin_error": "管理者をBANすることはできません！",
        "ban_error": "ユーザーのBAN中にエラーが発生しました：{error}",
        "silent_ban_error": "ユーザーを静かにBAN中にエラーが発生しました：{error}",
        "tban_usage": "使用法：/tban [user_id/reply] [duration] to（例：1h、30m、2d）",
        "tban_duration_invalid": "無効な期間フォーマット！[number][s|m|h|d|w]を使用してください（例：1h、30m、2d）",
        "tban_duration_too_long": "期間は366日を超えることはできません！",
        "tban_success": "ユーザー {user} が {duration} の間一時的にBANされました！ {admin} によるアクション",
        "tban_error": "ユーザーを一時的にBAN中にエラーが発生しました：{error}",
        "dban_no_reply": "/dbanを使用するにはメッセージに返信してください！",
        "dban_success": "ユーザー {user} がBANされ、メッセージが削除されました！ {admin} によるアクション",
        "dban_delete_error": "ユーザーはBANされましたが、メッセージの削除に失敗しました：{error}",
        "dban_error": "BANおよびメッセージ削除中にエラーが発生しました：{error}",
        "rban_success": "ユーザー {user} が {duration} の間ランダムにBANされました！ {admin} によるアクション",
        "rban_error": "ユーザーをランダムにBAN中にエラーが発生しました：{error}",
        "unexpected_error": "予期しないエラー：{error}",
        # New rules.py translations
        "no_rules_set": "このチャットにはルールが設定されていません。",
        "view_private_rules": "以下のボタンをクリックしてルールを表示：",
        "setrules_usage": "ルールのテキストを指定してください。使用法：/setrules [text]",
        "rules_updated": "ルールが正常に更新されました！このディープリンクでルールを共有：{deep_link}",
        "privaterules_usage": "使用法：/privaterules [yes/no/on/off]",
        "privaterules_status": "プライベートルールが {status}。",
        "rules_reset": "ルールがデフォルトにリセットされました。",
        "setrulesbutton_usage": "ボタンの名前を指定してください。使用法：/setrulesbutton [name]",
        "rulesbutton_set": "ルールボタンの名前が {button_name} に設定されました。",
        "rulesbutton_reset": "ルールボタンの名前がデフォルトにリセットされました。"
    },
    "ZH-TW": {
        # Existing admins.py translations
        "must_be_admin": "您必須是管理員才能使用此命令。",
        "no_permission_promote_demote": "您沒有權限提升或降級用戶。",
        "error_checking_admin": "檢查管理員狀態時出錯：{error}",
        "error_checking_permissions": "檢查權限時出錯：{error}",
        "promote_usage": "用法 → /promote [user_id] 或回覆用戶訊息。\n\n或 /promote [user_id] [title]。\n\n或 /promote [user_id] [title] [duration]。\n（例如，/promote 123366 版主 1d）",
        "invalid_user_ref": "無效的用戶引用。",
        "user_not_found": "在此聊天中未找到用戶：{error}",
        "invalid_duration_format": "無效的持續時間格式：{duration}。請使用 m、h 或 d（例如，30m、2h、1d）。",
        "duration_positive": "持續時間必須是正值。",
        "title_too_long": "標題必須為 16 個字符或更少！",
        "already_admin": "{user} 已經是管理員。",
        "promote_success": "成功提升 {user}\n\n權限：\n- 更改資訊：是\n- 刪除訊息：是\n- 限制成員：是\n- 邀請用戶：是\n- 置頂訊息：是\n- 提升成員：否\n- 管理視頻聊天：是",
        "title_set": "\n\n標題設置：{title}",
        "duration_set": "\n持續時間：{duration}",
        "promote_failed": "提升失敗：{error}",
        "no_permission_promote": "我沒有權限提升用戶。",
        "too_many_admins": "管理員過多！最多 50 個。",
        "user_not_member": "用戶不是此聊天的成員。",
        "demote_usage": "用法 → /demote [user_id] 或回覆用戶訊息。\n\n或 /demote [user_id]。",
        "cannot_demote_owner": "您無法降級群主。",
        "not_admin": "{user} 不是管理員。",
        "demote_success": "成功降級 {user}\n\n權限：\n- 更改資訊：否\n- 刪除訊息：否\n- 限制成員：否\n- 邀請用戶：否\n- 置頂訊息：否\n- 提升成員：否\n- 管理視頻聊天：否",
        "demote_failed": "降級失敗：{error}",
        "no_permission_demote": "我沒有權限降級用戶！",
        "no_admins_found": "未找到管理員。",
        "admin_list": "{chat_title} 中的管理員\n{admin_list}",
        "admin_list_failed": "無法檢索管理員列表：{error}",
        "cache_refreshed": "管理員快取已成功刷新。",
        "cache_refresh_failed": "快取刷新失敗：{error}",
        "anonadmin_status": "匿名管理員模式當前為 {status}。",
        "anonadmin_updated": "匿名管理員模式 {status}！",
        "adminerror_status": "管理員錯誤訊息當前為 {status}。",
        "adminerror_updated": "管理員錯誤訊息 {status}！",
        "adminerror_failed": "無法更新設置：{error}",
        "setlan_usage": "用法：/setlan [language_code]\n可用語言：{languages}",
        "invalid_language": "無效的語言代碼：{code}。請使用 /setlan 查看可用語言。",
        "language_updated": "語言設置為 {language}。",
        # Existing bans.py translations
        "no_user_id": "請回覆一條訊息或提供用戶ID！",
        "cannot_ban_admin": "無法封禁管理員或群主！",
        "cannot_ban_bot": "無法封禁機器人！",
        "already_banned": "用戶已被封禁！",
        "ban_success": "用戶 {user} 已被封禁！由 {admin} 執行",
        "no_permission_ban": "我沒有權限封禁用戶！請檢查我的管理員權限。",
        "ban_admin_error": "無法封禁管理員！",
        "ban_error": "封禁用戶時出錯：{error}",
        "silent_ban_error": "靜默封禁用戶時出錯：{error}",
        "tban_usage": "用法：/tban [user_id/reply] [duration]（例如，1h、30m、2d）",
        "tban_duration_invalid": "無效的持續時間格式！請使用 [number][s|m|h|d|w]（例如，1h、30m、2d）",
        "tban_duration_too_long": "持續時間不能超過366天！",
        "tban_success": "用戶 {user} 已被臨時封禁 {duration}！由 {admin} 執行",
        "tban_error": "臨時封禁用戶時出錯：{error}",
        "dban_no_reply": "請回覆一條訊息以使用 /dban！",
        "dban_success": "用戶 {user} 已被封禁，其訊息已刪除！由 {admin} 執行",
        "dban_delete_error": "用戶已封禁，但刪除訊息失敗：{error}",
        "dban_error": "封禁並刪除訊息時出錯：{error}",
        "rban_success": "用戶 {user} 已被隨機封禁 {duration}！由 {admin} 執行",
        "rban_error": "隨機封禁用戶時出錯：{error}",
        "unexpected_error": "意外錯誤：{error}",
        # New rules.py translations
        "no_rules_set": "此聊天未設置規則。",
        "view_private_rules": "請點擊下方按鈕查看規則：",
        "setrules_usage": "請提供規則文本。使用方法：/setrules [text]",
        "rules_updated": "規則已成功更新！使用此深度連結分享規則：{deep_link}",
        "privaterules_usage": "使用方法：/privaterules [yes/no/on/off]",
        "privaterules_status": "私有規則 {status}。",
        "rules_reset": "規則已重置為默認。",
        "setrulesbutton_usage": "請提供按鈕名稱。使用方法：/setrulesbutton [name]",
        "rulesbutton_set": "規則按鈕名稱已設置為：{button_name}",
        "rulesbutton_reset": "規則按鈕名稱已重置為默認。"
    }
}

# Rest of language.py remains unchanged
SUPPORTED_LANGUAGES = {
    "EN-GB": "English",
    "HI": "हिन्दी",
    "AR": "العربية",
    "ZH-CN": "中文 (简体)",
    "JA": "日本語",
    "ZH-TW": "繁體中文"
}

def read_language_data():
    """Read language settings from file."""
    try:
        if os.path.exists(LANGUAGE_FILE):
            with open(LANGUAGE_FILE, 'r') as f:
                return json.load(f)
        return {"chat_languages": {}}
    except Exception as e:
        print(f"Error reading language data: {e}")
        return {"chat_languages": {}}

def write_language_data(data):
    """Write language settings to file."""
    try:
        with open(LANGUAGE_FILE, 'w') as f:
            json.dump(data, f, indent=4)
    except Exception as e:
        print(f"Error writing language data: {e}")

def get_chat_language(chat_id):
    """Get the language setting for a chat."""
    data = read_language_data()
    return data.get("chat_languages", {}).get(str(chat_id), DEFAULT_LANGUAGE)

def set_chat_language(chat_id, language_code):
    """Set the language for a chat."""
    data = read_language_data()
    data["chat_languages"][str(chat_id)] = language_code
    write_language_data(data)

def get_translation(chat_id, key, **kwargs):
    """Get translated text for a given key and chat."""
    lang = get_chat_language(chat_id)
    translation = TRANSLATIONS.get(lang, TRANSLATIONS[DEFAULT_LANGUAGE]).get(
        key, TRANSLATIONS[DEFAULT_LANGUAGE].get(key, key)
    )
    return translation.format(**kwargs)